/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appleshop;

import javax.swing.JFrame;

/**
 *
 * @author Asus
 */
public class MenuBar11 extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public MenuBar11() {
        initComponents();
    }
      private void setMenuForRole(String role) {
        
        switch (role) {
            case "Manager":
                // Enable all menu options for the manager
                jMenuItemAddANewProduct.setEnabled(true);
                jMenuItemCreateAccount.setEnabled(true);
                break;
            case "Cashier":
                // Disable specific menu options for the cashier
                jMenuItemAddANewProduct.setEnabled(false);
                jMenuItemCreateAccount.setEnabled(false);
                break;
            default:
                // Disable all menu options for unknown roles or no role specified
               jMenuItemAddANewProduct.setEnabled(false);
                jMenuItemCreateAccount.setEnabled(false);
                break;
        }
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuProduct = new javax.swing.JMenu();
        jMenuItemViewAllProducts = new javax.swing.JMenuItem();
        jMenuItemSearchAProduct = new javax.swing.JMenuItem();
        jMenuStock = new javax.swing.JMenu();
        jMenuItemSearchStockDetails = new javax.swing.JMenuItem();
        jMenuExit = new javax.swing.JMenu();
        jMenuItemLogout = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuNew = new javax.swing.JMenu();
        jMenuItemAddANewProduct = new javax.swing.JMenuItem();
        jMenuItemCreateAccount = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));

        jLabel1.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" Welcome to AppleIshop Istore");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        jMenuProduct.setText("Products");

        jMenuItemViewAllProducts.setText("View all Products");
        jMenuItemViewAllProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewAllProductsActionPerformed(evt);
            }
        });
        jMenuProduct.add(jMenuItemViewAllProducts);

        jMenuItemSearchAProduct.setText("Search A Product");
        jMenuItemSearchAProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSearchAProductActionPerformed(evt);
            }
        });
        jMenuProduct.add(jMenuItemSearchAProduct);

        jMenuBar1.add(jMenuProduct);

        jMenuStock.setText("Stocks");

        jMenuItemSearchStockDetails.setText("Search Stock details");
        jMenuItemSearchStockDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSearchStockDetailsActionPerformed(evt);
            }
        });
        jMenuStock.add(jMenuItemSearchStockDetails);

        jMenuBar1.add(jMenuStock);

        jMenuExit.setText("Exit");

        jMenuItemLogout.setText("Logout and Login into another Account");
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jMenuExit.add(jMenuItemLogout);

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuExit.add(jMenuItemExit);

        jMenuBar1.add(jMenuExit);

        jMenuNew.setText("New");

        jMenuItemAddANewProduct.setText("Add a New Product");
        jMenuItemAddANewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddANewProductActionPerformed(evt);
            }
        });
        jMenuNew.add(jMenuItemAddANewProduct);

        jMenuItemCreateAccount.setText("Create a New Account");
        jMenuItemCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCreateAccountActionPerformed(evt);
            }
        });
        jMenuNew.add(jMenuItemCreateAccount);

        jMenuBar1.add(jMenuNew);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSearchAProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSearchAProductActionPerformed
        // TODO add your handling code here:
      SearchAProduct sap = new SearchAProduct();
        sap.setVisible(true);
        sap.pack();
        sap.setLocationRelativeTo(null);
        sap.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_jMenuItemSearchAProductActionPerformed

    private void jMenuItemAddANewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddANewProductActionPerformed
        // TODO add your handling code here:
        AddNewProducts anp = new AddNewProducts();
        anp.setVisible(false);
        anp.pack();
        anp.setLocationRelativeTo(null);
        anp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jMenuItemAddANewProductActionPerformed

    private void jMenuItemViewAllProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewAllProductsActionPerformed
        // TODO add your handling code here:
        ViewAllProducts vap = new ViewAllProducts();
        vap.setVisible(true);
        vap.pack();
        vap.setLocationRelativeTo(null);
        vap.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jMenuItemViewAllProductsActionPerformed

    private void jMenuItemCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCreateAccountActionPerformed
        // TODO add your handling code here:
        CreateAccount rgf = new CreateAccount();
        rgf.setVisible(false);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jMenuItemCreateAccountActionPerformed

    private void jMenuItemSearchStockDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSearchStockDetailsActionPerformed
        // TODO add your handling code here:
        SearchStock ss = new SearchStock();
        ss.setVisible(true);
        ss.pack();
        ss.setLocationRelativeTo(null);
        ss.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jMenuItemSearchStockDetailsActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        // TODO add your handling code here:
       // Close the current window
    dispose();
  
    // Open a new login window
    LoginUI loginWindow = new LoginUI();
    loginWindow.setVisible(false);
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            MenuBar11 menuBarFrame = new MenuBar11();
            menuBarFrame.setVisible(true);

            

            String Username2 = "cashier"; // Placeholder, replace with actual username input
            String Password2 = "2222"; // Placeholder, replace with actual password input

           
            String loggedInRole2 = login(Username2, Password2); // Perform login and get the role

            
        }
    });
}


private static String login(String Username, String Password) {
    // Placeholder login logic
    // Here, you would typically query a database or perform authentication to determine the role based on the username and password
    // For this example, let's assume the roles are "Manager" and "Cashier" based on the username

    if (Username.equals("Cashier") && Password.equals("2222")) {
        return "Cashier";
    } else {
        return "Manager";
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuExit;
    private javax.swing.JMenuItem jMenuItemAddANewProduct;
    private javax.swing.JMenuItem jMenuItemCreateAccount;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemSearchAProduct;
    private javax.swing.JMenuItem jMenuItemSearchStockDetails;
    private javax.swing.JMenuItem jMenuItemViewAllProducts;
    private javax.swing.JMenu jMenuNew;
    private javax.swing.JMenu jMenuProduct;
    private javax.swing.JMenu jMenuStock;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    

    
}
